# Generated by Django 4.2.2 on 2023-07-02 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactEmailInformation',
            fields=[
                ('email_information_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('email_user', models.CharField(max_length=255)),
                ('email_information', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPhoneInformation',
            fields=[
                ('phone_information_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('phone_user', models.CharField(max_length=255)),
                ('phone_information', models.CharField(max_length=255)),
            ],
        ),
    ]
